#/bin/bash 
#quickpkg --include-config y # Quickpackage lystem apps
### 
quickpkg --include-config y app-accessibility/*
quickpkg --include-config y app-admin/*
quickpkg --include-config y app-arch/*
quickpkg --include-config y app-backup/*
quickpkg --include-config y app-cdr/*
quickpkg --include-config y app-crypt/*
quickpkg --include-config y app-editors/*
quickpkg --include-config y app-emulation/*
quickpkg --include-config y app-eselect/*
quickpkg --include-config y app-forensics/*
quickpkg --include-config y app-fuzz/*
quickpkg --include-config y app-laptop/*
quickpkg --include-config y app-misc/*
quickpkg --include-config y app-mobilephone/*
quickpkg --include-config y app-office/*
quickpkg --include-config y app-pda/*
quickpkg --include-config y app-portage/*
quickpkg --include-config y app-shells/*
quickpkg --include-config y dev-cpp/*
quickpkg --include-config y dev-db/*
quickpkg --include-config y dev-embedded/*
quickpkg --include-config y dev-java/*
quickpkg --include-config y dev-lang/*
quickpkg --include-config y  dev-lua/*
quickpkg --include-config y dev-perl/* 
quickpkg --include-config y dev-python/* 
quickpkg --include-config y dev-qt/* 
quickpkg --include-config y dev-ruby/* 
quickpkg --include-config y dev-scheme/* 
quickpkg --include-config y dev-tcltk/* 
quickpkg --include-config y dev-util/* 
quickpkg --include-config y gnome-base/*
quickpkg --include-config y java-virtuals/* 
quickpkg --include-config y mail-client/* 
quickpkg --include-config y dev-texlive/* 
quickpkg --include-config y virtual/* 
quickpkg --include-config y media-gfx/* 
quickpkg --include-config y media-libs/*
quickpkg --include-config y media-plugins/*
quickpkg --include-config y media-radio/*
quickpkg --include-config y media-sound/*
quickpkg --include-config y media-video/*
quickpkg --include-config y net-dialup/*
quickpkg --include-config y net-dns/*
quickpkg --include-config y net-ftp/*
quickpkg --include-config y net-irc/*
quickpkg --include-config y net-libs/*
quickpkg --include-config y net-misc/*
quickpkg --include-config y net-proxy/*
quickpkg --include-config y net-voip/*
quickpkg --include-config y net-analyzer/*
quickpkg --include-config y pentoo/*
quickpkg --include-config y perl-core/*
quickpkg --include-config y sci-geosciences/*
quickpkg --include-config y sci-libs/*
quickpkg --include-config y sys-apps/*
quickpkg --include-config y sci-mathematics/*
quickpkg --include-config y sci-visualization/*
quickpkg --include-config y sys-auth/*
quickpkg --include-config y sys-boot/*
quickpkg --include-config y sys-devel/*
quickpkg --include-config y sys-cluster/*
quickpkg --include-config y sys-firmware/*
quickpkg --include-config y sys-fs/*
quickpkg --include-config y sys-kernel/*
quickpkg --include-config y sys-libs/*
quickpkg --include-config y sys-power/*
quickpkg --include-config y sys-process/*
quickpkg --include-config y virtual/*
quickpkg --include-config y www-apps/*
quickpkg --include-config y x11-apps/*
quickpkg --include-config y x11-base/*
quickpkg --include-config y x11-libs/*
quickpkg --include-config y x11-misc/*
quickpkg --include-config y x11-proto/*
quickpkg --include-config y xfce-extra/*